#!/bin/bash
# Static Hands Advanced - Auto Installer

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=================================="
echo "Static Hands Advanced - Installer"
echo "=================================="
echo ""
echo "📂 Working directory: $SCRIPT_DIR"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
   echo "❌ Don't run this script as root!"
   exit 1
fi

echo "📦 Step 1/7: Installing dependencies..."

# Detect package manager
if command -v apt &> /dev/null; then
    sudo apt update
    sudo apt install -y wget
elif command -v dnf &> /dev/null; then
    sudo dnf install -y wget
elif command -v pacman &> /dev/null; then
    sudo pacman -Sy --noconfirm wget
else
    echo "⚠️ Unsupported package manager. Install wget manually."
    exit 1
fi

echo "✅ Dependencies installed"
echo ""

echo "📥 Step 2/7: Downloading Kanata..."
KANATA_VERSION="v1.7.0"
cd ~/Downloads
wget -q https://github.com/jtroo/kanata/releases/download/${KANATA_VERSION}/kanata
chmod +x kanata
sudo mv kanata /usr/local/bin/
cd "$SCRIPT_DIR"
echo "✅ Kanata installed to /usr/local/bin/"
echo ""

echo "📂 Step 3/7: Setting up configuration directory..."
mkdir -p ~/.config/kanata

cp config_advanced.kbd ~/.config/kanata/config.kbd || {
    echo "❌ Error: Could not copy config_advanced.kbd"
    echo "   Make sure you're in the correct directory"
    exit 1
}

echo "✅ Config file copied"
echo ""

echo "🔧 Step 4/7: Disabling CapsLock system behavior..."

# Detect desktop environment
if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || [ "$XDG_CURRENT_DESKTOP" = "ubuntu:GNOME" ]; then
    gsettings set org.gnome.desktop.input-sources xkb-options "['caps:none']"
    echo "✅ CapsLock disabled (GNOME)"
elif [ "$XDG_CURRENT_DESKTOP" = "KDE" ]; then
    if command -v kwriteconfig5 &> /dev/null; then
        kwriteconfig5 --file kxkbrc --group Layout --key Options caps:none
        echo "✅ CapsLock disabled (KDE - will apply after logout)"
    else
        setxkbmap -option caps:none
        echo "✅ CapsLock disabled (KDE - using setxkbmap)"
    fi
else
    setxkbmap -option caps:none
    echo "✅ CapsLock disabled (generic)"
fi
echo ""

echo "👥 Step 5/7: Setting up permissions..."
sudo groupadd -f uinput
sudo usermod -aG input,uinput $USER

# Create udev rule for Fedora/RHEL
if [ -f /etc/redhat-release ]; then
    echo 'KERNEL=="uinput", MODE="0666", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/rules.d/99-uinput.rules > /dev/null
    sudo udevadm control --reload-rules
    sudo udevadm trigger
    echo "✅ Fedora-specific udev rules applied"
else
    echo 'KERNEL=="uinput", GROUP="uinput", MODE="0660", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/rules.d/99-uinput.rules > /dev/null
    sudo udevadm control --reload-rules
    sudo udevadm trigger
    echo "✅ Standard udev rules applied"
fi
echo ""

echo "🚀 Step 6/7: Creating systemd service..."
mkdir -p ~/.config/systemd/user

cat > ~/.config/systemd/user/kanata.service << 'EOF'
[Unit]
Description=Kanata keyboard remapper
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/local/bin/kanata -c %h/.config/kanata/config.kbd
Restart=always

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable kanata.service
echo "✅ Service created and enabled"
echo ""

echo "🔄 Step 7/7: Starting Kanata..."

# Handle SELinux on Fedora
if command -v getenforce &> /dev/null; then
    if [ "$(getenforce)" = "Enforcing" ]; then
        echo "⚠️ SELinux detected. Temporarily setting to Permissive..."
        sudo setenforce 0
    fi
fi

systemctl --user start kanata.service
sleep 1

if systemctl --user is-active --quiet kanata.service; then
    echo "✅ Kanata is running!"
else
    echo "⚠️ Kanata failed to start. Check logs:"
    echo "   journalctl --user -u kanata.service -n 20"
    exit 1
fi

# Create autostart script for post-reboot
cat > ~/.kanata-autostart.sh << 'AUTOSTART_EOF'
#!/bin/bash
# Auto-generated by Static Hands Advanced installer
# This script runs once after first reboot to enable Kanata

if ! systemctl --user is-enabled kanata.service &>/dev/null; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  🚀 Enabling Kanata service..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    systemctl --user daemon-reload
    systemctl --user enable --now kanata.service
    
    sleep 1
    
    if systemctl --user is-active kanata.service &>/dev/null; then
        echo "✅ Kanata is now running!"
        echo "Test it: Press CapsLock+I/J/K/L for arrows"
        echo ""
    else
        echo "❌ Error starting Kanata"
        echo "Check status: systemctl --user status kanata.service"
        echo ""
    fi
fi

# Self-destruct after successful run
rm -f ~/.kanata-autostart.sh
sed -i '/kanata-autostart\.sh/d' ~/.bash_profile 2>/dev/null
AUTOSTART_EOF

chmod +x ~/.kanata-autostart.sh

# Add to .bash_profile if not already present
if ! grep -q "kanata-autostart.sh" ~/.bash_profile 2>/dev/null; then
    echo "" >> ~/.bash_profile
    echo "# Auto-start Kanata after first reboot (added by Static Hands installer)" >> ~/.bash_profile
    echo '[ -f ~/.kanata-autostart.sh ] && ~/.kanata-autostart.sh' >> ~/.bash_profile
fi

echo ""
echo "=================================="
echo "✅ INSTALLATION COMPLETE!"
echo "=================================="
echo ""
echo "🎯 Active features: 30/39"
echo ""
echo "📋 What works:"
echo "  ✅ All navigation (IJKL, UO, YN, H, ;, P)"
echo "  ✅ All modifiers (F, D, S, W)"
echo "  ✅ Text editing (A, Z, X, C, V, B)"
echo "  ✅ Speed navigation (8, ,, M, .)"
echo "  ✅ Special keys (Q, R, T, 7, \`, F7)"
echo ""
echo "⚠️ Limitations:"
echo "  • Case change (9, 0, -) - requires recompiling Kanata with cmd flag"
echo "  • Always On Top (=) - configure in your window manager"
echo "  • Help window (F10) - use README instead"
echo "  • Google Search (Alt+G) - use browser shortcuts"
echo ""
echo "🔄 IMPORTANT:"
echo "  1. REBOOT your system"
echo "  2. After reboot, Kanata will auto-enable on first login ✨"
echo "  3. OR run manually: systemctl --user enable --now kanata.service"
echo ""
echo "📖 More info: README_ADVANCED.md"
echo "❓ Troubleshooting: INSTALL_ADVANCED.md"
echo ""
