#!/bin/bash
#
# Static Hands Quick Installer
# Linux Kanata keyboard remapper setup
#
# Usage: bash install.sh
#

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=========================================="
echo "  Static Hands - Quick Install"
echo "=========================================="
echo ""
echo "📂 Working directory: $SCRIPT_DIR"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo "❌ ERROR: Do not run as root/sudo"
    echo "   The script will ask for sudo when needed"
    exit 1
fi

echo "This script will:"
echo "  1. Install dependencies (wget)"
echo "  2. Download and install Kanata"
echo "  3. Configure permissions"
echo "  4. Disable CapsLock system behavior"
echo "  5. Install config and systemd service"
echo "  6. Prompt you to reboot"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

echo ""
echo "[1/6] Installing dependencies..."
# Detect package manager and install wget
if command -v apt &> /dev/null; then
    sudo apt update && sudo apt install -y wget
    echo "✓ Dependencies installed (apt)"
elif command -v dnf &> /dev/null; then
    sudo dnf install -y wget
    echo "✓ Dependencies installed (dnf)"
elif command -v pacman &> /dev/null; then
    sudo pacman -Sy --noconfirm wget
    echo "✓ Dependencies installed (pacman)"
else
    echo "⚠️  Could not detect package manager"
    echo "   Please install wget manually: sudo <pkg-manager> install wget"
    exit 1
fi

echo ""
echo "[2/6] Downloading and installing Kanata..."
cd /tmp
wget -q --show-progress https://github.com/jtroo/kanata/releases/download/v1.7.0/kanata
chmod +x kanata
sudo mv kanata /usr/local/bin/
cd "$SCRIPT_DIR"
echo "✓ Kanata installed"

echo ""
echo "[3/6] Configuring permissions..."
sudo groupadd -f uinput
sudo usermod -aG input,uinput $USER
sudo modprobe uinput

# Distribution-specific udev rules
if [ -f /etc/redhat-release ]; then
    # Fedora/RHEL: MODE="0666" works best
    echo 'KERNEL=="uinput", MODE="0666", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/rules.d/99-uinput.rules > /dev/null
    echo "✓ udev rule configured (Fedora/RHEL)"
else
    # Debian/Ubuntu/Arch: MODE="0660" + GROUP="uinput"
    echo 'KERNEL=="uinput", GROUP="uinput", MODE="0660", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/rules.d/99-uinput.rules > /dev/null
    echo "✓ udev rule configured (Debian/Ubuntu/Arch)"
fi

# Auto-load module on boot
echo 'uinput' | sudo tee /etc/modules-load.d/uinput.conf > /dev/null
sudo udevadm control --reload-rules
sudo udevadm trigger

# Immediate permission fix (works on all distros)
sudo chmod 0666 /dev/uinput
echo "✓ Permissions configured"

echo ""
echo "[4/6] Disabling CapsLock system behavior..."
# Detect desktop environment and disable CapsLock accordingly
if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || [ "$XDG_CURRENT_DESKTOP" = "ubuntu:GNOME" ]; then
    gsettings set org.gnome.desktop.input-sources xkb-options "['caps:none']"
    echo "✓ CapsLock disabled (GNOME)"
elif [ "$XDG_CURRENT_DESKTOP" = "KDE" ]; then
    if command -v kwriteconfig5 &> /dev/null; then
        kwriteconfig5 --file kxkbrc --group Layout --key Options caps:none
        qdbus org.kde.keyboard /Layouts org.kde.KeyboardLayouts.reconfigure 2>/dev/null || true
        echo "✓ CapsLock disabled (KDE)"
    else
        setxkbmap -option caps:none 2>/dev/null || true
        echo "✓ CapsLock disabled (setxkbmap)"
    fi
else
    # Fallback for other desktop environments
    if command -v setxkbmap &> /dev/null; then
        setxkbmap -option caps:none
        echo "✓ CapsLock disabled (setxkbmap)"
    else
        echo "⚠️  Could not disable CapsLock automatically"
        echo "   Please disable it manually in your DE settings"
    fi
fi

echo ""
echo "[5/6] Installing config and service..."
mkdir -p ~/.config/kanata
if [ -f "$SCRIPT_DIR/config.kbd" ]; then
    cp "$SCRIPT_DIR/config.kbd" ~/.config/kanata/config.kbd
    echo "✓ Config installed from: $SCRIPT_DIR/config.kbd"
else
    echo "⚠️  config.kbd not found in: $SCRIPT_DIR"
    echo "   Please copy it manually to ~/.config/kanata/config.kbd"
fi

mkdir -p ~/.config/systemd/user/
cat > ~/.config/systemd/user/kanata.service << 'EOF'
[Unit]
Description=Kanata keyboard remapper
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/local/bin/kanata -c %h/.config/kanata/config.kbd
Restart=always

[Install]
WantedBy=default.target
EOF
echo "✓ Systemd service created"

# Create autostart script for post-reboot
cat > ~/.kanata-autostart.sh << 'AUTOSTART_EOF'
#!/bin/bash
# Auto-generated by Static Hands installer
# This script runs once after first reboot to enable Kanata

if ! systemctl --user is-enabled kanata.service &>/dev/null; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  🚀 Enabling Kanata service..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    systemctl --user daemon-reload
    systemctl --user enable --now kanata.service
    
    sleep 1
    
    if systemctl --user is-active kanata.service &>/dev/null; then
        echo "✅ Kanata is now running!"
        echo "Test it: Press CapsLock+H/J/K/L for arrows"
        echo ""
    else
        echo "❌ Error starting Kanata"
        echo "Check status: systemctl --user status kanata.service"
        echo ""
    fi
fi

# Self-destruct after successful run
rm -f ~/.kanata-autostart.sh
sed -i '/kanata-autostart\.sh/d' ~/.bash_profile 2>/dev/null
AUTOSTART_EOF

chmod +x ~/.kanata-autostart.sh

# Add to .bash_profile if not already present
if ! grep -q "kanata-autostart.sh" ~/.bash_profile 2>/dev/null; then
    echo "" >> ~/.bash_profile
    echo "# Auto-start Kanata after first reboot (added by Static Hands installer)" >> ~/.bash_profile
    echo '[ -f ~/.kanata-autostart.sh ] && ~/.kanata-autostart.sh' >> ~/.bash_profile
fi

echo ""
echo "[6/6] Setup complete!"
echo ""
echo "=========================================="
echo "  IMPORTANT: REBOOT REQUIRED"
echo "=========================================="
echo ""
echo "Group changes only apply after reboot."
echo "After rebooting:"
echo "  → Kanata will auto-enable on first login ✨"
echo "  → OR run manually: systemctl --user enable --now kanata.service"
echo ""
read -p "Reboot now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Rebooting..."
    sudo reboot
else
    echo ""
    echo "Remember to reboot before using Static Hands!"
fi
